apiVersion: v1
kind: ConfigMap
metadata:
  name: ranking
  labels:
    app: ranking
  namespace: development
data:
  RABBIT_HOST: "rabbitmq-rabbitmq"
  RABBIT_PORT: "5672"
  MONGO_HOST: "mongodb-mongodb"
  MONGO_PORT: "27017"
  ENV_SPRING: "prod"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: ranking
  namespace: development
type: Opaque
data:
  MONGO_USER: c2Vuc2VkaWEtYmV0
  MONGO_PASS: YmV0QDIwMTg=
  RABBIT_USER: c2Vuc2VkaWEtYmV0
  RABBIT_PASS: YmV0QDIwMTg=
---
kind: Service
apiVersion: v1
metadata:
  name: ranking
  labels:
    app: ranking
  namespace: development
spec:
  selector:
    app: ranking
  ports:
  - name: http
    port: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ranking
  labels:
    app: ranking
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ranking
        tier: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ranking
        image: gcr.io/sensedia-bet/ranking:latest
        env:
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: RABBIT_HOST
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: RABBIT_PORT
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: MONGO_PORT
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: ENV_SPRING
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: ranking
              key: RABBIT_USER
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: ranking
              key: RABBIT_PASS
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: ranking
              key: MONGO_USER
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: ranking
              key: MONGO_PASS
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: REDIS_PORT
        ports:
        - name: http
          containerPort: 8888
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 30
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 30
