apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "wc-gateway"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "world-cup-2018"
spec:
  hosts:
  - "*"
  gateways:
  - "wc-gateway"
  http:
  - match:
    - uri:
        prefix: /api/matches
    route:
    - destination:
        host: "game-data"
        port:
          number: 7777
  - match:
    - uri:
        exact: /matches
    route:
    - destination:
        host: "game-data-proxy"
        port:
          number: 9999