apiVersion: v1
kind: Service
metadata:
  labels:
    app: spinnaker-deck
  name: spinnaker-deck-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: spinnaker-deck-http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: spinnaker-spinnaker
    component: deck
  sessionAffinity: None
  type: LoadBalancer